# Perfil DEV: ejecucion local con MySQL de XAMPP (localhost:3306)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_clientes?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: texdigital
    password: texdigital123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
