spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth/**

        - id: auth-service-usuarios
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/api/usuarios/**

        - id: ms-clientes
          uri: ${MS_CLIENTES_URL}
          predicates:
            - Path=/api/clientes/**

        - id: ms-inventario-textiles
          uri: ${MS_INVENTARIO_URL}
          predicates:
            - Path=/api/textiles/**

        - id: ms-inventario-rollos
          uri: ${MS_INVENTARIO_URL}
          predicates:
            - Path=/api/rollos/**

        - id: ms-pagos
          uri: ${MS_PAGOS_URL}
          predicates:
            - Path=/api/pagos/**

        - id: ms-pedidos
          uri: ${MS_PEDIDOS_URL}
          predicates:
            - Path=/api/pedidos/**

        - id: ms-produccion
          uri: ${MS_PRODUCCION_URL}
          predicates:
            - Path=/api/ordenes/**

        - id: ms-productos
          uri: ${MS_PRODUCTOS_URL}
          predicates:
            - Path=/api/productos/**

        - id: ms-resenas
          uri: ${MS_RESENAS_URL}
          predicates:
            - Path=/api/resenas/**
